
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 16;
  public static final int READ = 8;
  public static final int OVER = 17;
  public static final int LT = 12;
  public static final int ELSE = 4;
  public static final int PLUS = 14;
  public static final int RPAREN = 19;
  public static final int THEN = 3;
  public static final int SEMI = 20;
  public static final int END = 5;
  public static final int ERROR = 23;
  public static final int IF = 2;
  public static final int LPAREN = 18;
  public static final int GT = 13;
  public static final int ID = 21;
  public static final int WRITE = 9;
  public static final int NUM = 22;
  public static final int EOF = 0;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int UNTIL = 7;
  public static final int ASSIGN = 10;
  public static final int EQ = 11;
  public static final int REPEAT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "ASSIGN",
  "EQ",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "ID",
  "NUM",
  "ERROR"
  };
}

